apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: my-service
  endpoints:
    - targetPort: 8081
      interval: 10s
      path: "/metrics"
  namespaceSelector:
    matchNames:
      - default